import { addDays, format, subDays } from "date-fns";
import type {
  Customer,
  Invoice,
  Material,
  RateChange,
  Rental,
  ReturnRecord,
  Settings,
} from "@/types";

const iso = (date: Date) => date.toISOString();
const day = (offset: number) => format(subDays(new Date(), offset), "yyyy-MM-dd");
const dayAhead = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const stamp = (offset: number) => iso(subDays(new Date(), offset));

export const defaultSettings: Settings = {
  shopName: "BuildRent Shuttering Store",
  address: "Shop 14, Kharar–Landran Road, Sector 91, Mohali, Punjab 140301",
  phone: "+91 98765 43210",
  gstNumber: "03ABCDE1234F1Z5",
  invoicePrefix: "INV",
  currency: "INR",
  dayCountConvention: "exclusive",
  minimumBillableDays: 1,
  defaultPaymentStatus: "pending",
  invoiceNotes:
    "Rent is charged per day from the issue date. Damaged or unreturned material is billed at replacement cost.",
  units: ["piece", "set", "bundle", "other"],
  categories: ["Shuttering", "Support", "Timber", "Scaffolding", "Accessories"],
  theme: "system",
  sidebarCollapsed: false,
};

export const mockMaterials: Material[] = [
  {
    id: "MAT-0001",
    name: "Fatte",
    localName: "ਫੱਟੇ",
    category: "Timber",
    unit: "piece",
    totalStock: 400,
    availableStock: 280,
    dailyRate: 10,
    isActive: true,
    description: "Seasoned wooden planks, 8 ft × 9 in, used for slab shuttering decks.",
    createdAt: stamp(220),
    updatedAt: stamp(30),
  },
  {
    id: "MAT-0002",
    name: "Ghodi",
    localName: "ਘੋੜੀ",
    category: "Support",
    unit: "piece",
    totalStock: 180,
    availableStock: 155,
    dailyRate: 20,
    isActive: true,
    description: "Adjustable trestle supports for slab and beam shuttering.",
    createdAt: stamp(220),
    updatedAt: stamp(45),
  },
  {
    id: "MAT-0003",
    name: "Shuttering Plate",
    localName: "ਸ਼ਟਰਿੰਗ ਪਲੇਟ",
    category: "Shuttering",
    unit: "piece",
    totalStock: 260,
    availableStock: 225,
    dailyRate: 15,
    isActive: true,
    description: "3 ft × 2 ft MS centering plates, 3 mm sheet with angle framing.",
    createdAt: stamp(210),
    updatedAt: stamp(60),
  },
  {
    id: "MAT-0004",
    name: "Prop",
    localName: "ਪ੍ਰੌਪ",
    category: "Support",
    unit: "piece",
    totalStock: 220,
    availableStock: 148,
    dailyRate: 25,
    isActive: true,
    description: "Telescopic steel props, 2 m to 3.5 m, with base and top plate.",
    createdAt: stamp(210),
    updatedAt: stamp(18),
  },
  {
    id: "MAT-0005",
    name: "Wooden Beam",
    localName: "ਲੱਕੜ ਦਾ ਸ਼ਤੀਰ",
    category: "Timber",
    unit: "piece",
    totalStock: 120,
    availableStock: 92,
    dailyRate: 30,
    isActive: true,
    description: "H16 timber beams for primary and secondary slab support.",
    createdAt: stamp(190),
    updatedAt: stamp(90),
  },
  {
    id: "MAT-0006",
    name: "Scaffolding Pipe",
    category: "Scaffolding",
    unit: "piece",
    totalStock: 300,
    availableStock: 246,
    dailyRate: 12,
    isActive: true,
    description: "10 ft MS pipes, 48 mm outer diameter.",
    createdAt: stamp(160),
    updatedAt: stamp(120),
  },
  {
    id: "MAT-0007",
    name: "Coupler Set",
    category: "Accessories",
    unit: "set",
    totalStock: 150,
    availableStock: 150,
    dailyRate: 8,
    isActive: true,
    description: "Right-angle and swivel couplers, 25 pieces per set.",
    createdAt: stamp(150),
    updatedAt: stamp(150),
  },
  {
    id: "MAT-0008",
    name: "Wall Clamp",
    category: "Shuttering",
    unit: "piece",
    totalStock: 90,
    availableStock: 90,
    dailyRate: 18,
    isActive: false,
    description: "Column and wall shuttering clamps. Out of service for repairs.",
    createdAt: stamp(140),
    updatedAt: stamp(12),
  },
];

export const mockRateChanges: RateChange[] = [
  {
    id: "RC-0001",
    materialId: "MAT-0001",
    previousRate: 8,
    newRate: 10,
    changedAt: stamp(30),
    changedBy: "Gurpreet Singh",
  },
  {
    id: "RC-0002",
    materialId: "MAT-0004",
    previousRate: 22,
    newRate: 25,
    changedAt: stamp(18),
    changedBy: "Gurpreet Singh",
  },
  {
    id: "RC-0003",
    materialId: "MAT-0003",
    previousRate: 12,
    newRate: 15,
    changedAt: stamp(60),
    changedBy: "Gurpreet Singh",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "CUS-0001",
    name: "Raj Kumar",
    phone: "9876543210",
    address: "House 221, Phase 7, Mohali",
    idProof: "Aadhaar ····4421",
    notes: "Regular customer. Usually takes material for slab work.",
    createdAt: stamp(180),
  },
  {
    id: "CUS-0002",
    name: "Harpreet Singh Sandhu",
    phone: "9814500221",
    address: "Village Landran, near Gurudwara Sahib",
    idProof: "Aadhaar ····9087",
    createdAt: stamp(150),
  },
  {
    id: "CUS-0003",
    name: "Balwinder Construction Co.",
    phone: "9878001122",
    address: "Plot 8, Industrial Area Phase 2, Chandigarh",
    notes: "Contractor account. Settles bills at month end.",
    createdAt: stamp(140),
  },
  {
    id: "CUS-0004",
    name: "Manjit Kaur",
    phone: "9646711900",
    address: "Sector 70, Mohali",
    createdAt: stamp(96),
  },
  {
    id: "CUS-0005",
    name: "Jaspal Thekedar",
    phone: "9915223344",
    address: "Kharar bypass, near petrol pump",
    notes: "Takes props and plates for column work.",
    createdAt: stamp(75),
  },
  {
    id: "CUS-0006",
    name: "Sukhdev Sharma",
    phone: "9781234567",
    address: "Zirakpur, VIP Road",
    createdAt: stamp(40),
  },
  {
    id: "CUS-0007",
    name: "Amrit Builders",
    phone: "9592008877",
    address: "Sector 115, Mohali",
    createdAt: stamp(22),
  },
];

export const mockRentals: Rental[] = [
  // Active, open-ended — the everyday case.
  {
    id: "REN-1001",
    customerId: "CUS-0001",
    items: [
      {
        id: "RI-1001-1",
        materialId: "MAT-0001",
        materialName: "Fatte",
        quantity: 60,
        returnedQuantity: 0,
        dailyRate: 10,
        unit: "piece",
      },
      {
        id: "RI-1001-2",
        materialId: "MAT-0002",
        materialName: "Ghodi",
        quantity: 25,
        returnedQuantity: 0,
        dailyRate: 20,
        unit: "piece",
      },
    ],
    issueDate: day(6),
    notes: "Slab casting at Phase 7 site.",
    status: "active",
    createdAt: stamp(6),
  },
  // Active with a partial return already recorded.
  {
    id: "REN-1002",
    customerId: "CUS-0003",
    items: [
      {
        id: "RI-1002-1",
        materialId: "MAT-0003",
        materialName: "Shuttering Plate",
        quantity: 60,
        returnedQuantity: 25,
        dailyRate: 15,
        unit: "piece",
      },
      {
        id: "RI-1002-2",
        materialId: "MAT-0004",
        materialName: "Prop",
        quantity: 40,
        returnedQuantity: 0,
        dailyRate: 25,
        unit: "piece",
      },
    ],
    issueDate: day(12),
    expectedReturnDate: dayAhead(6),
    notes: "Column shuttering, Industrial Area site.",
    status: "active",
    createdAt: stamp(12),
  },
  // Overdue — expected return date has passed.
  {
    id: "REN-1003",
    customerId: "CUS-0005",
    items: [
      {
        id: "RI-1003-1",
        materialId: "MAT-0004",
        materialName: "Prop",
        quantity: 32,
        returnedQuantity: 0,
        dailyRate: 22,
        unit: "piece",
      },
      {
        id: "RI-1003-2",
        materialId: "MAT-0006",
        materialName: "Scaffolding Pipe",
        quantity: 54,
        returnedQuantity: 0,
        dailyRate: 12,
        unit: "piece",
      },
    ],
    issueDate: day(24),
    expectedReturnDate: day(4),
    notes: "Two-storey scaffolding at Kharar bypass.",
    status: "active",
    createdAt: stamp(24),
  },
  {
    id: "REN-1004",
    customerId: "CUS-0002",
    items: [
      {
        id: "RI-1004-1",
        materialId: "MAT-0001",
        materialName: "Fatte",
        quantity: 60,
        returnedQuantity: 0,
        dailyRate: 8,
        unit: "piece",
      },
      {
        id: "RI-1004-2",
        materialId: "MAT-0005",
        materialName: "Wooden Beam",
        quantity: 28,
        returnedQuantity: 0,
        dailyRate: 30,
        unit: "piece",
      },
    ],
    issueDate: day(9),
    notes: "Locked at the old ₹8 Fatte rate from before the September revision.",
    status: "active",
    createdAt: stamp(9),
  },
  // Closed rentals with invoices.
  {
    id: "REN-0996",
    customerId: "CUS-0001",
    items: [
      {
        id: "RI-0996-1",
        materialId: "MAT-0001",
        materialName: "Fatte",
        quantity: 40,
        returnedQuantity: 40,
        dailyRate: 8,
        unit: "piece",
      },
      {
        id: "RI-0996-2",
        materialId: "MAT-0002",
        materialName: "Ghodi",
        quantity: 20,
        returnedQuantity: 20,
        dailyRate: 20,
        unit: "piece",
      },
    ],
    issueDate: day(45),
    actualReturnDate: day(38),
    status: "returned",
    createdAt: stamp(45),
  },
  {
    id: "REN-0997",
    customerId: "CUS-0004",
    items: [
      {
        id: "RI-0997-1",
        materialId: "MAT-0003",
        materialName: "Shuttering Plate",
        quantity: 35,
        returnedQuantity: 35,
        dailyRate: 12,
        unit: "piece",
      },
    ],
    issueDate: day(34),
    actualReturnDate: day(28),
    status: "returned",
    createdAt: stamp(34),
  },
  {
    id: "REN-0998",
    customerId: "CUS-0003",
    items: [
      {
        id: "RI-0998-1",
        materialId: "MAT-0004",
        materialName: "Prop",
        quantity: 50,
        returnedQuantity: 50,
        dailyRate: 22,
        unit: "piece",
      },
      {
        id: "RI-0998-2",
        materialId: "MAT-0006",
        materialName: "Scaffolding Pipe",
        quantity: 80,
        returnedQuantity: 80,
        dailyRate: 12,
        unit: "piece",
      },
    ],
    issueDate: day(30),
    actualReturnDate: day(20),
    status: "returned",
    createdAt: stamp(30),
  },
  {
    id: "REN-0999",
    customerId: "CUS-0006",
    items: [
      {
        id: "RI-0999-1",
        materialId: "MAT-0001",
        materialName: "Fatte",
        quantity: 25,
        returnedQuantity: 25,
        dailyRate: 8,
        unit: "piece",
      },
    ],
    issueDate: day(18),
    actualReturnDate: day(14),
    status: "returned",
    createdAt: stamp(18),
  },
  {
    id: "REN-1000",
    customerId: "CUS-0007",
    items: [
      {
        id: "RI-1000-1",
        materialId: "MAT-0005",
        materialName: "Wooden Beam",
        quantity: 18,
        returnedQuantity: 18,
        dailyRate: 30,
        unit: "piece",
      },
      {
        id: "RI-1000-2",
        materialId: "MAT-0002",
        materialName: "Ghodi",
        quantity: 18,
        returnedQuantity: 18,
        dailyRate: 20,
        unit: "piece",
      },
    ],
    issueDate: day(11),
    actualReturnDate: day(3),
    status: "returned",
    createdAt: stamp(11),
  },
  // A draft the admin started but has not issued yet — stock untouched.
  {
    id: "REN-1005",
    customerId: "CUS-0004",
    items: [
      {
        id: "RI-1005-1",
        materialId: "MAT-0003",
        materialName: "Shuttering Plate",
        quantity: 20,
        returnedQuantity: 0,
        dailyRate: 15,
        unit: "piece",
      },
    ],
    issueDate: day(0),
    notes: "Customer will confirm quantity tomorrow morning.",
    status: "draft",
    createdAt: stamp(0),
  },
];

export const mockReturns: ReturnRecord[] = [
  {
    id: "RET-0001",
    rentalId: "REN-1002",
    materialId: "MAT-0003",
    materialName: "Shuttering Plate",
    quantity: 25,
    returnDate: day(3),
    notes: "First floor columns stripped.",
  },
  {
    id: "RET-0002",
    rentalId: "REN-0996",
    materialId: "MAT-0001",
    materialName: "Fatte",
    quantity: 40,
    returnDate: day(38),
  },
  {
    id: "RET-0003",
    rentalId: "REN-0996",
    materialId: "MAT-0002",
    materialName: "Ghodi",
    quantity: 20,
    returnDate: day(38),
  },
  {
    id: "RET-0004",
    rentalId: "REN-0997",
    materialId: "MAT-0003",
    materialName: "Shuttering Plate",
    quantity: 35,
    returnDate: day(28),
  },
  {
    id: "RET-0005",
    rentalId: "REN-0998",
    materialId: "MAT-0004",
    materialName: "Prop",
    quantity: 50,
    returnDate: day(20),
  },
  {
    id: "RET-0006",
    rentalId: "REN-0998",
    materialId: "MAT-0006",
    materialName: "Scaffolding Pipe",
    quantity: 80,
    returnDate: day(20),
  },
  {
    id: "RET-0007",
    rentalId: "REN-0999",
    materialId: "MAT-0001",
    materialName: "Fatte",
    quantity: 25,
    returnDate: day(14),
  },
  {
    id: "RET-0008",
    rentalId: "REN-1000",
    materialId: "MAT-0005",
    materialName: "Wooden Beam",
    quantity: 18,
    returnDate: day(3),
  },
  {
    id: "RET-0009",
    rentalId: "REN-1000",
    materialId: "MAT-0002",
    materialName: "Ghodi",
    quantity: 18,
    returnDate: day(3),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "INV-0001",
    rentalId: "REN-0996",
    customerId: "CUS-0001",
    issueDate: day(45),
    returnDate: day(38),
    totalDays: 7,
    subtotal: 5040,
    damageCharges: 0,
    additionalCharges: 200,
    discount: 240,
    totalAmount: 5000,
    paidAmount: 5000,
    status: "paid",
    notes: "Transport charge added for site delivery.",
    createdAt: stamp(38),
  },
  {
    id: "INV-0002",
    rentalId: "REN-0997",
    customerId: "CUS-0004",
    issueDate: day(34),
    returnDate: day(28),
    totalDays: 6,
    subtotal: 2520,
    damageCharges: 300,
    additionalCharges: 0,
    discount: 0,
    totalAmount: 2820,
    paidAmount: 2820,
    status: "paid",
    notes: "Two plates returned bent — repair charge applied.",
    createdAt: stamp(28),
  },
  {
    id: "INV-0003",
    rentalId: "REN-0998",
    customerId: "CUS-0003",
    issueDate: day(30),
    returnDate: day(20),
    totalDays: 10,
    subtotal: 20600,
    damageCharges: 0,
    additionalCharges: 0,
    discount: 600,
    totalAmount: 20000,
    paidAmount: 10000,
    status: "partial",
    notes: "Contractor account — balance due at month end.",
    createdAt: stamp(20),
  },
  {
    id: "INV-0004",
    rentalId: "REN-0999",
    customerId: "CUS-0006",
    issueDate: day(18),
    returnDate: day(14),
    totalDays: 4,
    subtotal: 800,
    damageCharges: 0,
    additionalCharges: 0,
    discount: 0,
    totalAmount: 800,
    paidAmount: 0,
    status: "pending",
    createdAt: stamp(14),
  },
  {
    id: "INV-0005",
    rentalId: "REN-1000",
    customerId: "CUS-0007",
    issueDate: day(11),
    returnDate: day(3),
    totalDays: 8,
    subtotal: 7200,
    damageCharges: 0,
    additionalCharges: 0,
    discount: 0,
    totalAmount: 7200,
    paidAmount: 7200,
    status: "paid",
    createdAt: stamp(3),
  },
];

export const currentAdmin = {
  name: "Gurpreet Singh",
  role: "Shop owner",
  phone: "+91 98765 43210",
};
